using System.Linq;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using NUnit.Framework;

namespace Moirai.SourceGenerators.Tests;

public class SampleIncrementalSourceGeneratorTests
{
    private const string VectorClassText = @"
namespace TestNamespace;

[Generators.EnumFromConstants(""C"", ""c_"")]
public partial class Vector3
{
    public const int c_x = 1;
    public const int c_y = 2;
    public const int c_z = 3;
}";

    private const string ExpectedGeneratedClassText = @"// <auto-generated/>

using System;

namespace TestNamespace;

partial class Vector3
{
    public enum C
    {
        X = Vector3.c_x,
        Y = Vector3.c_y,
        Z = Vector3.c_z,
    }
}
";

    [Test]
    public void GenerateReportMethod()
    {
        // Create an instance of the source generator.
        var generator = new SampleIncrementalSourceGenerator();

        // Source generators should be tested using 'GeneratorDriver'.
        var driver = CSharpGeneratorDriver.Create(generator);

        // We need to create a compilation with the required source code.
        var compilation = CSharpCompilation.Create(nameof(SampleIncrementalSourceGeneratorTests),
            new[] { CSharpSyntaxTree.ParseText(VectorClassText) },
            new[]
            {
                // To support 'System.Attribute' inheritance, add reference to 'System.Private.CoreLib'.
                MetadataReference.CreateFromFile(typeof(object).Assembly.Location)
            });

        // Run generators and retrieve all results.
        var runResult = driver.RunGenerators(compilation).GetRunResult();

        // All generated files can be found in 'RunResults.GeneratedTrees'.
        var generatedFileSyntax = runResult.GeneratedTrees.Single(t => t.FilePath.EndsWith("Vector3.g.cs"));

        // Complex generators should be tested using text comparison. NUnit has no built-in
        // ignore-line-endings option, so normalise both sides before comparing.
        Assert.That(
            generatedFileSyntax.GetText().ToString().Replace("\r\n", "\n"),
            Is.EqualTo(ExpectedGeneratedClassText.Replace("\r\n", "\n")));
    }
}
