grammar storygen;
r: LINE_BREAK* action+ ;
action: ACTION_ID LINE_BREAK effect (effect)* ;
effect: (create | set | assign) SPACE* LINE_BREAK+ SPACE*;
set: 'set'  path '=' value;
value: path | bool | NULL ;
NULL: 'null';
bool: 'true' | 'false';
create: 'create' ID;
assign: VAR_ID '=' call;
call : ID '(' expr (',' expr)* ')';
expr : ID op value ;
op : '=' | '!=' ;
path : VAR_ID ('.' ID)* | ID;
VAR_ID: '$' [a-z][a-z_]*;
ACTION_ID: '@' [a-z][a-z_]*;
ID : [a-z][a-z_]* ;
SPACE: [ \t]+ -> skip;
LINE_BREAK: ('\r\n' | '\r' | '\n');
